package com.xb.busmore.dao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xb.busmore.entity.AllLineInfo;
import com.xb.busmore.entity.BlackListEntity;
import com.xb.busmore.entity.car.CarConfig;
import com.xb.busmore.entity.car.CarRunInfo;
import com.xb.busmore.entity.car.UseConfig;
import com.xb.busmore.entity.LineInfoUp;
import com.xb.busmore.entity.LinePriceInfo;
import com.xb.busmore.entity.LineStation;
import com.xb.busmore.entity.ScanInfoEntity;
import com.xb.busmore.moudle.qrCode.entity.FTPEntity;
import com.xb.busmore.moudle.qrCode.entity.MacKeyEntity;
import com.xb.busmore.moudle.qrCode.entity.PublicKeyEntity;
import com.xb.busmore.moudle.unionpay.entity.UnionAidEntity;
import com.xb.busmore.moudle.unionpay.entity.UnionPayEntity;
import com.xb.busmore.moudle.card.CardRecord;

import com.xb.busmore.dao.db.AllLineInfoDao;
import com.xb.busmore.dao.db.BlackListEntityDao;
import com.xb.busmore.dao.db.CarConfigDao;
import com.xb.busmore.dao.db.CarRunInfoDao;
import com.xb.busmore.dao.db.UseConfigDao;
import com.xb.busmore.dao.db.LineInfoUpDao;
import com.xb.busmore.dao.db.LinePriceInfoDao;
import com.xb.busmore.dao.db.LineStationDao;
import com.xb.busmore.dao.db.ScanInfoEntityDao;
import com.xb.busmore.dao.db.FTPEntityDao;
import com.xb.busmore.dao.db.MacKeyEntityDao;
import com.xb.busmore.dao.db.PublicKeyEntityDao;
import com.xb.busmore.dao.db.UnionAidEntityDao;
import com.xb.busmore.dao.db.UnionPayEntityDao;
import com.xb.busmore.dao.db.CardRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig allLineInfoDaoConfig;
    private final DaoConfig blackListEntityDaoConfig;
    private final DaoConfig carConfigDaoConfig;
    private final DaoConfig carRunInfoDaoConfig;
    private final DaoConfig useConfigDaoConfig;
    private final DaoConfig lineInfoUpDaoConfig;
    private final DaoConfig linePriceInfoDaoConfig;
    private final DaoConfig lineStationDaoConfig;
    private final DaoConfig scanInfoEntityDaoConfig;
    private final DaoConfig fTPEntityDaoConfig;
    private final DaoConfig macKeyEntityDaoConfig;
    private final DaoConfig publicKeyEntityDaoConfig;
    private final DaoConfig unionAidEntityDaoConfig;
    private final DaoConfig unionPayEntityDaoConfig;
    private final DaoConfig cardRecordDaoConfig;

    private final AllLineInfoDao allLineInfoDao;
    private final BlackListEntityDao blackListEntityDao;
    private final CarConfigDao carConfigDao;
    private final CarRunInfoDao carRunInfoDao;
    private final UseConfigDao useConfigDao;
    private final LineInfoUpDao lineInfoUpDao;
    private final LinePriceInfoDao linePriceInfoDao;
    private final LineStationDao lineStationDao;
    private final ScanInfoEntityDao scanInfoEntityDao;
    private final FTPEntityDao fTPEntityDao;
    private final MacKeyEntityDao macKeyEntityDao;
    private final PublicKeyEntityDao publicKeyEntityDao;
    private final UnionAidEntityDao unionAidEntityDao;
    private final UnionPayEntityDao unionPayEntityDao;
    private final CardRecordDao cardRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        allLineInfoDaoConfig = daoConfigMap.get(AllLineInfoDao.class).clone();
        allLineInfoDaoConfig.initIdentityScope(type);

        blackListEntityDaoConfig = daoConfigMap.get(BlackListEntityDao.class).clone();
        blackListEntityDaoConfig.initIdentityScope(type);

        carConfigDaoConfig = daoConfigMap.get(CarConfigDao.class).clone();
        carConfigDaoConfig.initIdentityScope(type);

        carRunInfoDaoConfig = daoConfigMap.get(CarRunInfoDao.class).clone();
        carRunInfoDaoConfig.initIdentityScope(type);

        useConfigDaoConfig = daoConfigMap.get(UseConfigDao.class).clone();
        useConfigDaoConfig.initIdentityScope(type);

        lineInfoUpDaoConfig = daoConfigMap.get(LineInfoUpDao.class).clone();
        lineInfoUpDaoConfig.initIdentityScope(type);

        linePriceInfoDaoConfig = daoConfigMap.get(LinePriceInfoDao.class).clone();
        linePriceInfoDaoConfig.initIdentityScope(type);

        lineStationDaoConfig = daoConfigMap.get(LineStationDao.class).clone();
        lineStationDaoConfig.initIdentityScope(type);

        scanInfoEntityDaoConfig = daoConfigMap.get(ScanInfoEntityDao.class).clone();
        scanInfoEntityDaoConfig.initIdentityScope(type);

        fTPEntityDaoConfig = daoConfigMap.get(FTPEntityDao.class).clone();
        fTPEntityDaoConfig.initIdentityScope(type);

        macKeyEntityDaoConfig = daoConfigMap.get(MacKeyEntityDao.class).clone();
        macKeyEntityDaoConfig.initIdentityScope(type);

        publicKeyEntityDaoConfig = daoConfigMap.get(PublicKeyEntityDao.class).clone();
        publicKeyEntityDaoConfig.initIdentityScope(type);

        unionAidEntityDaoConfig = daoConfigMap.get(UnionAidEntityDao.class).clone();
        unionAidEntityDaoConfig.initIdentityScope(type);

        unionPayEntityDaoConfig = daoConfigMap.get(UnionPayEntityDao.class).clone();
        unionPayEntityDaoConfig.initIdentityScope(type);

        cardRecordDaoConfig = daoConfigMap.get(CardRecordDao.class).clone();
        cardRecordDaoConfig.initIdentityScope(type);

        allLineInfoDao = new AllLineInfoDao(allLineInfoDaoConfig, this);
        blackListEntityDao = new BlackListEntityDao(blackListEntityDaoConfig, this);
        carConfigDao = new CarConfigDao(carConfigDaoConfig, this);
        carRunInfoDao = new CarRunInfoDao(carRunInfoDaoConfig, this);
        useConfigDao = new UseConfigDao(useConfigDaoConfig, this);
        lineInfoUpDao = new LineInfoUpDao(lineInfoUpDaoConfig, this);
        linePriceInfoDao = new LinePriceInfoDao(linePriceInfoDaoConfig, this);
        lineStationDao = new LineStationDao(lineStationDaoConfig, this);
        scanInfoEntityDao = new ScanInfoEntityDao(scanInfoEntityDaoConfig, this);
        fTPEntityDao = new FTPEntityDao(fTPEntityDaoConfig, this);
        macKeyEntityDao = new MacKeyEntityDao(macKeyEntityDaoConfig, this);
        publicKeyEntityDao = new PublicKeyEntityDao(publicKeyEntityDaoConfig, this);
        unionAidEntityDao = new UnionAidEntityDao(unionAidEntityDaoConfig, this);
        unionPayEntityDao = new UnionPayEntityDao(unionPayEntityDaoConfig, this);
        cardRecordDao = new CardRecordDao(cardRecordDaoConfig, this);

        registerDao(AllLineInfo.class, allLineInfoDao);
        registerDao(BlackListEntity.class, blackListEntityDao);
        registerDao(CarConfig.class, carConfigDao);
        registerDao(CarRunInfo.class, carRunInfoDao);
        registerDao(UseConfig.class, useConfigDao);
        registerDao(LineInfoUp.class, lineInfoUpDao);
        registerDao(LinePriceInfo.class, linePriceInfoDao);
        registerDao(LineStation.class, lineStationDao);
        registerDao(ScanInfoEntity.class, scanInfoEntityDao);
        registerDao(FTPEntity.class, fTPEntityDao);
        registerDao(MacKeyEntity.class, macKeyEntityDao);
        registerDao(PublicKeyEntity.class, publicKeyEntityDao);
        registerDao(UnionAidEntity.class, unionAidEntityDao);
        registerDao(UnionPayEntity.class, unionPayEntityDao);
        registerDao(CardRecord.class, cardRecordDao);
    }
    
    public void clear() {
        allLineInfoDaoConfig.clearIdentityScope();
        blackListEntityDaoConfig.clearIdentityScope();
        carConfigDaoConfig.clearIdentityScope();
        carRunInfoDaoConfig.clearIdentityScope();
        useConfigDaoConfig.clearIdentityScope();
        lineInfoUpDaoConfig.clearIdentityScope();
        linePriceInfoDaoConfig.clearIdentityScope();
        lineStationDaoConfig.clearIdentityScope();
        scanInfoEntityDaoConfig.clearIdentityScope();
        fTPEntityDaoConfig.clearIdentityScope();
        macKeyEntityDaoConfig.clearIdentityScope();
        publicKeyEntityDaoConfig.clearIdentityScope();
        unionAidEntityDaoConfig.clearIdentityScope();
        unionPayEntityDaoConfig.clearIdentityScope();
        cardRecordDaoConfig.clearIdentityScope();
    }

    public AllLineInfoDao getAllLineInfoDao() {
        return allLineInfoDao;
    }

    public BlackListEntityDao getBlackListEntityDao() {
        return blackListEntityDao;
    }

    public CarConfigDao getCarConfigDao() {
        return carConfigDao;
    }

    public CarRunInfoDao getCarRunInfoDao() {
        return carRunInfoDao;
    }

    public UseConfigDao getUseConfigDao() {
        return useConfigDao;
    }

    public LineInfoUpDao getLineInfoUpDao() {
        return lineInfoUpDao;
    }

    public LinePriceInfoDao getLinePriceInfoDao() {
        return linePriceInfoDao;
    }

    public LineStationDao getLineStationDao() {
        return lineStationDao;
    }

    public ScanInfoEntityDao getScanInfoEntityDao() {
        return scanInfoEntityDao;
    }

    public FTPEntityDao getFTPEntityDao() {
        return fTPEntityDao;
    }

    public MacKeyEntityDao getMacKeyEntityDao() {
        return macKeyEntityDao;
    }

    public PublicKeyEntityDao getPublicKeyEntityDao() {
        return publicKeyEntityDao;
    }

    public UnionAidEntityDao getUnionAidEntityDao() {
        return unionAidEntityDao;
    }

    public UnionPayEntityDao getUnionPayEntityDao() {
        return unionPayEntityDao;
    }

    public CardRecordDao getCardRecordDao() {
        return cardRecordDao;
    }

}
