package com.xb.busmore.dao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.xb.busmore.entity.LinePriceInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LINE_PRICE_INFO".
*/
public class LinePriceInfoDao extends AbstractDao<LinePriceInfo, Long> {

    public static final String TABLENAME = "LINE_PRICE_INFO";

    /**
     * Properties of entity LinePriceInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property No = new Property(1, int.class, "no", false, "NO");
        public final static Property Price = new Property(2, int.class, "price", false, "PRICE");
        public final static Property Line = new Property(3, String.class, "line", false, "LINE");
        public final static Property Diraction = new Property(4, int.class, "diraction", false, "DIRACTION");
        public final static Property Time = new Property(5, Long.class, "time", false, "TIME");
    }


    public LinePriceInfoDao(DaoConfig config) {
        super(config);
    }
    
    public LinePriceInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LINE_PRICE_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NO\" INTEGER NOT NULL ," + // 1: no
                "\"PRICE\" INTEGER NOT NULL ," + // 2: price
                "\"LINE\" TEXT," + // 3: line
                "\"DIRACTION\" INTEGER NOT NULL ," + // 4: diraction
                "\"TIME\" INTEGER);"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LINE_PRICE_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LinePriceInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNo());
        stmt.bindLong(3, entity.getPrice());
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(4, line);
        }
        stmt.bindLong(5, entity.getDiraction());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LinePriceInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNo());
        stmt.bindLong(3, entity.getPrice());
 
        String line = entity.getLine();
        if (line != null) {
            stmt.bindString(4, line);
        }
        stmt.bindLong(5, entity.getDiraction());
 
        Long time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LinePriceInfo readEntity(Cursor cursor, int offset) {
        LinePriceInfo entity = new LinePriceInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // no
            cursor.getInt(offset + 2), // price
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // line
            cursor.getInt(offset + 4), // diraction
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LinePriceInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNo(cursor.getInt(offset + 1));
        entity.setPrice(cursor.getInt(offset + 2));
        entity.setLine(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDiraction(cursor.getInt(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LinePriceInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LinePriceInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LinePriceInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
